name: flutter_instagram_stories
homepage: https://github.com/awaik/flutter_instagram_stories
description: Display stories (videos and images) like Whatsapp & Instagram.
version: 1.0.3

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.5
  video_player: ^2.4.7
  cached_network_image: ^3.2.2
  flutter_cache_manager: ^3.3.0
  firebase_core: ^2.0.0
  cloud_firestore: ^4.0.1
  # dotted_border: any
  dotted_border: ^2.0.0+3
  # json_annotation: any
  json_annotation: ^4.7.0
  # collection: any
  collection: ^1.16.0

dev_dependencies:
  # build_runner: any
  build_runner: ^2.3.3
  # json_serializable: any
  json_serializable: ^6.5.4
  # flutter_lints: any
  flutter_lints: ^2.0.1

false_secrets:
  - /example/lib/firebase_options.dart
  - /example/android/app/google-services.json
